"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Cargar variables del archivo .env si existe (sin librerías externas)
_env_file = Path(__file__).resolve().parent.parent / '.env'
if _env_file.exists():
    with open(_env_file, encoding='utf-8') as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith('#') and '=' in _line:
                _key, _val = _line.split('=', 1)
                os.environ.setdefault(_key.strip(), _val.strip())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Lee desde .env — ver backend/.env.example para instrucciones
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-clave-solo-para-desarrollo-local-no-usar-en-produccion'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto es False para 'fallar seguro' en producción.
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# En producción: TI DEBE definir el dominio en .env. Si no se define y DEBUG=False, el sistema no responderá.
_allowed = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()] if _allowed else ([] if not DEBUG else ['*'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    'axes',
    'auditlog',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    # Local
    'continuidad',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'axes.middleware.AxesMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
]

# CORS: en desarrollo permite todo, en producción solo el dominio del frontend
# Configurar en .env: CORS_ALLOWED_ORIGINS=https://sgcn.empresa.com
_cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()] if _cors_origins else []
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Solo permite todo si DEBUG=True
CORS_ALLOW_CREDENTIALS = True   # NECESARIO para que las cookies httpOnly viajen en peticiones cross-origin

# CSRF - Orígenes de confianza (incluye el origen del frontend)
_csrf_raw = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = (
    [o.strip() for o in _csrf_raw.split(',') if o.strip()]
    if _csrf_raw else
    ['http://localhost:5173', 'http://127.0.0.1:5173']
)

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'continuidad.validators.CustomPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Lee el token JWT desde cookie httpOnly (protege contra XSS)
        # Fallback: también acepta header Authorization: Bearer para Postman/API tools
        'continuidad.cookie_auth.CookieJWTAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
        'otp_verify': '5/minute',  # Límite estricto para intentos de OTP
        'otp_send': '3/minute',    # Límite para reenvío de correos
    }
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Autenticación y Seguridad avanzada
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Configuración de AXES (Protección contra fuerza bruta)
AXES_FAILURE_LIMIT = 5         # Bloqueo tras 5 intentos
AXES_COOLOFF_TIME = 24         # Bloqueo por 24 horas
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
AXES_RESET_ON_SUCCESS = True   # Limpiar contador al entrar con éxito
AXES_ONLY_USER_FAILURES = True # No bloquear la IP completa, solo el usuario en esa IP

# --- CORREO (Microsoft 365 / Outlook corporativo) ---
# Configurar en .env con los datos reales de la cuenta de correo corporativa.
# TI debe habilitar "SMTP Auth" para la cuenta en el Microsoft 365 Admin Center.
#
# Variables requeridas en .env para producción:
#   EMAIL_HOST_USER=notificaciones@empresa.com
#   EMAIL_HOST_PASSWORD=<contraseña de la cuenta>
#   DEFAULT_FROM_EMAIL=notificaciones@empresa.com

_email_user = os.environ.get('EMAIL_HOST_USER', '')

if _email_user:
    # Producción: usar SMTP real de Microsoft 365
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.office365.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = _email_user
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', _email_user)
else:
    # Desarrollo local: imprime el correo en la consola del servidor (no envía nada)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'dev@localhost'

# --- CABECERAS DE SEGURIDAD ---
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Activar automáticamente en producción (cuando DEBUG=False)
# Solo funcionan con HTTPS — TI debe configurar el certificado SSL primero
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000          # Forzar HTTPS por 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True              # Redirigir HTTP → HTTPS
    SESSION_COOKIE_SECURE = True            # Cookies solo por HTTPS
    CSRF_COOKIE_SECURE = True               # CSRF solo por HTTPS
    # Las cookies de JWT también necesitan secure=True — ya configuradas en views.py

# --- LOGGING ESTRUCTURADO ---
# Fix #7: guarda errores en archivo con rotación automática
# Logs en: backend/logs/errors.log (se crea la carpeta si no existe)
# Rotación: máximo 5MB por archivo, 3 archivos de respaldo
import os
LOGS_DIR = BASE_DIR / 'logs'
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {module}: {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'file_errors': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 5 * 1024 * 1024,  # 5MB
            'backupCount': 3,
            'formatter': 'verbose',
            'level': 'WARNING',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file_errors'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['file_errors'],
            'level': 'ERROR',
            'propagate': False,
        },
        'continuidad': {
            # Logger para usar en nuestro propio código:
            # import logging; logger = logging.getLogger('continuidad')
            # logger.error("Algo falló", exc_info=True)
            'handlers': ['console', 'file_errors'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
