# Generated by Django 5.2.11 on 2026-02-10 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad', models.CharField(default='Bogotá', max_length=100)),
                ('direccion', models.CharField(max_length=300)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('criticidad', models.CharField(default='Normal', max_length=50)),
                ('rto', models.IntegerField(help_text='Recovery Time Objective (horas)')),
                ('rpo', models.IntegerField(help_text='Recovery Point Objective (horas)')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='continuidad.sede')),
            ],
            options={
                'verbose_name_plural': 'Procesos',
                'ordering': ['rto'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nivel_alerta', models.CharField(choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('naranja', 'Naranja'), ('rojo', 'Rojo')], default='verde', max_length=20)),
                ('geometria', models.TextField(blank=True, help_text='GeoJSON de la zona afectada')),
                ('sedes_afectadas', models.ManyToManyField(blank=True, related_name='eventos', to='continuidad.sede')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha'],
            },
        ),
    ]
