# Generated by Django 5.2.11 on 2026-02-17 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuidad', '0002_evento_creado_por_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('identificacion', models.CharField(help_text='Cédula o ID único', max_length=50, unique=True)),
                ('cargo', models.CharField(blank=True, max_length=150)),
                ('gerencia', models.CharField(blank=True, max_length=150)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Remoto', 'Remoto'), ('Hibrido', 'Híbrido')], default='Presencial', max_length=20)),
                ('direccion', models.CharField(blank=True, help_text='Dirección de residencia', max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('sede_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='continuidad.sede')),
            ],
            options={
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
