# Generated by Django 5.2.11 on 2026-02-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuidad', '0003_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='compania',
            field=models.CharField(blank=True, help_text='Empresa a la que pertenece', max_length=100),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
