# Generated by Django 5.2.11 on 2026-03-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuidad', '0004_colaborador_compania_colaborador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarcar si el colaborador ya no está en la empresa'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, help_text='Nombre del contacto en caso de emergencia', max_length=200),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, help_text='Teléfono del contacto en caso de emergencia', max_length=50),
        ),
    ]
