# Generated by Django 5.2.11 on 2026-03-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuidad', '0005_colaborador_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('hospital', 'Hospital / Clínica'), ('police', 'Estación de Policía / CAI'), ('fire_station', 'Estación de Bomberos'), ('emergency_center', 'Centro de Emergencias'), ('otro', 'Otro')], max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('fuente', models.CharField(default='IDECA Bogotá', help_text='Origen del dato', max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entidad de Apoyo',
                'verbose_name_plural': 'Red de Apoyo Oficial',
                'ordering': ['tipo', 'nombre'],
            },
        ),
    ]
